name: Go Lint

on:
  push:
    branches: [main]
    paths:
      - "frontend/**/*.go"
  pull_request:
    paths:
      - "frontend/**/*.go"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
    
      - name: Set up golangci
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Format
        working-directory: frontend
        run: make format-fe

      - name: Lint
        working-directory: frontend
        run: make lint-fe